<div align="center">

<h1 style="font-size: 22px;"><b>LAPORAN PRAKTIKUM</b></h1>

<h2 style="font-size: 18px;"><b>ALGORITMA DAN PEMROGRAMAN</b></h2>

<h2 style="font-size: 18px;"><b>“Pengenalan Tipe Data dan Variabel Python”</b></h2>

<h4 style="font-size: 16px;"><b>Disusun Oleh :</b></h4>

<h4 style="font-size: 16px;"><b>Rizki Ramadhani Al Michtari</b></h4>

<h4 style="font-size: 16px;"><b>2611532001</b><h4>

<h4 style="font-size: 16px;"><b>Dosen Pengampu:</b></h4>

<h4 style="font-size: 16px;"><b>Dr. Ir. Wahyudi, S.T., M.T.</b></h4>

<h4 style="font-size: 16px;"><b>Asisten Praktikum:</b></h4>

<h4 style="font-size: 16px;"><b>Rifki Yuliandra</b></h4>

</div>

<div align="center">

<img src="images/logo_unand.png" width="200">

</div>

<div align="center">

<h3 style="font-size: 18px;"><b>FAKULTAS TEKNOLOGI INFORMASI</b></h3>

<h3 style="font-size: 18px;"><b>DEPARTEMEN INFORMATIKA</b></h3>

<h3 style="font-size: 18px;"><b>UNIVERSITAS ANDALAS</b></h3>

<h3 style="font-size: 18px;"><b>2026</b></h3>


</div>

<div align="center">

<h1><b>KATA PENGANTAR</b></h1>

</div>

Puji beserta syukur saya panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga saya dapat menyelesaikan laporan praktikum mengenai pengenalan tipe data dan variabel Python yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan jenis - jenis tipe data yang ada pada bahasa pemrograman Python.

Melalui praktikum ini, hasil yang diharapkan adalah saya dapat memahami secara langsung konsep mengenai macam - macam tipe data Python dan bisa mengindentifikasi nilai dari suatu variabel serta bisa mengelompokkan nilai variabel berdasarkan tipe datanya pada bahasa pemrograman Python.

Saya menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

Hormat saya,

(Rizki Ramadhani Al Michtari)

<div align="center>## KATA PENGANTAR<div>

Puji syukur penulis panjatkan kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga penulis dapat menyelesaikan laporan praktikum mengenai pengenalan Python, VS Code, dan pengkoneksian folder lokal ke reporitory GitHub yang telah dilaksanakan sebagai pertemuan ke-1 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan bagaimana cara memasang VS Code di komputer, ekstensi Python di VS Code, bikin kode Python, serta bagaimana cara menghubungkan VS Code dengan GitHub, dan _commit_ kode di VS Code ke GitHub.

Melalui praktikum ini, hasil yang diharapkan adalah penulis dapat memahami dan mengimplementasikan secara langsung konsep pembuatan kode program Python di VS Code serta melakukan _commit_ kode ke GitHub pada _real project_.

Penulis menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, September 2026

Penulis,

(Rizki Ramadhani Al Michtari)

---
<div align="center">

<h1><b>BAB I</b><h1>

<h1><b>PENDAHULUAN</b></h1>

</div>

<h2><b>1.1 Latar Belakang</b></h2>

Pada era perkembangan teknologi saat ini, seorang _developer_ atau _programmer_ dituntut untuk terus adaptif terhadap perkembangan bahasa pemrograman. Salah satu bahasa pemrograman yang sangat populer dan banyak digunakan di industri saat ini adalah Python. Python menjadi pilihan utama banyak pengembang karena sintaksisnya yang relatif sederhana, efisien, serta fleksibel untuk diaplikasikan dalam berbagai bidang, seperti pengembangan gim, kecerdasan buatan (_artificial intelligence_), hingga analisis data.

Dalam membangun suatu program dengan Python, terdapat komponen-komponen mendasar yang saling berkaitan, yaitu variabel, tipe data, serta fungsi masukan dan keluaran (_input/output_). Variabel berfungsi sebagai penampung data sementara di memori, sedangkan tipe data—seperti _string_, _integer_, _float_, maupun _boolean_—menentukan karakteristik nilai yang disimpan serta jenis operasi yang dapat dilakukan terhadapnya. Di samping itu, fungsi dasar seperti `input()` dan `print()` memungkinkan terjadinya interaksi antara pengguna dengan program. Pemahaman terhadap komponen-komponen dasar ini sangat krusial agar logika dan algoritma yang dirancang dapat berjalan sebagaimana mestinya tanpa menimbulkan _error_.

Berdasarkan urgensi tersebut, kegiatan praktikum ini dilaksanakan untuk memberikan pemahaman mendasar kepada mahasiswa mengenai konsep variabel, ragam tipe data, serta pengoperasian fungsi dasar pada Python. Praktikum ini menjadi fondasi yang sangat penting agar mahasiswa memiliki landasan yang kuat dalam mengoperasikan bahasa Python serta mampu mengembangkannya ke tingkat pemrograman yang lebih kompleks di masa mendatang.

<h2><b>1.2 Tujuan</b></h2>

1. Memahami fungsi variabel sebagai wadah penyimpanan data sementara serta aturan penulisan (_naming convention_) variabel pada bahasa pemrograman Python.
2. Mengidentifikasi dan membedakan berbagai tipe data dasar pada Python, seperti `int`, `float`, `str`, dan `bool`.
3. Mendeklarasikan variabel, melakukan operasi dasar pada tipe data, serta menerapkan konversi tipe data (_type casting_) secara tepat dalam program.
4. Mengenali kesalahan umum yang terjadi akibat ketidaksesuaian tipe data (_type error_) dan memperbaikinya saat mengeksekusi kode.

<h2><b>1.3 Manfaat</b></h2>

1. Memperoleh pemahaman mendasar yang kokoh mengenai variabel dan tipe data sebagai acuan utama untuk mempelajari topik pemrograman yang lebih kompleks, seperti struktur kendali dan fungsi.
2. Meningkatkan keterampilan dalam menulis, menjalankan, dan men-debug sintaksis dasar Python secara mandiri di lingkungan pengembangan (_IDE/environment_).
3. Mendapat keyakinan bahwa data yang diolah di dalam program telah menggunakan tipe data yang sesuai, sehingga meminimalkan potensi timbulnya bug atau error saat aplikasi dikembangkan lebih lanjut.

---
<div align="center">

<h1><b>BAB II</b><h1>

<h1><b>PEMBAHASAN</b></h1>

</div>

<h2><b>2.1 Landasan Teori</b></h2>

**1. Pengetahuan Umum Tentang Python**

Python merupakan bahasa pemrograman tingkat tinggi (_high-level language_) bersifat _general-purpose_ (tujuan umum) dan open-source. Diciptakan oleh Guido van Rossum, Python dirancang dengan penekanan pada keterbacaan kode (_code readability_) melalui penggunaan sintaksis yang sederhana dan mirip bahasa Inggris. Sifatnya yang _dynamically typed_ juga memungkinkan pengembang menulis program tanpa perlu mendeklarasikan tipe data secara eksplisit.

​Keunggulan utama Python terletak pada fleksibilitas dan ekosistem pustakanya (_library_) yang luas. Hal ini membuat Python populer digunakan di berbagai bidang, seperti pengembangan web (_web development_), otomatisasi tugas (_scripting_), hingga analisis data dan kecerdasan buatan.

​**2. Variabel, Tipe Data, dan Konversi Tipe Data**

**a. Variabel dalam Python:** ​Variabel merupakan tempat penyimpanan data atau nilai sementara di memori yang dapat digunakan dan diubah selama program berjalan. Pemrograman Python menerapkan sistem _dynamically typed_, yaitu kondisi di mana pengembang tidak perlu mendefinisikan tipe data secara eksplisit saat mendeklarasikan variabel. Pendeklarasian dilakukan langsung dengan menetapkan nilai pada nama variabel menggunakan operator penugasan (`=`).

​**b. Tipe Data Dasar:** ​Tipe data menentukan jenis nilai yang dapat disimpan di dalam variabel. Tipe data dasar dalam Python terdiri dari:
> * ​String (`str`): Kumpulan karakter atau teks yang diapit oleh tanda kutip (`"..."` atau `'...'`).
> * ​Integer (`int`): Nilai berupa bilangan bulat.
> * ​Float (`float`): Nilai berupa bilangan desimal.
> * ​Boolean (`bool`): Nilai logika yang hanya terdiri dari dua kondisi, yaitu `True` (benar) atau `False` (salah).

​**c. Konversi Tipe Data (_Type Casting_):** ​Konversi tipe data merupakan proses mengubah nilai dari satu tipe data ke tipe data lainnya secara eksplisit. Proses ini krusial dilakukan untuk memastikan kesesuaian tipe data saat pengolahan perintah, seperti operasi aritmetika maupun penggabungan teks. Sebagai contoh, fungsi `input()` secara bawaan akan menghasilkan output bertipe string. Jika data tersebut hendak digunakan dalam kalkulasi matematika, data harus dikonversi terlebih dahulu ke tipe `int` atau `float` menggunakan fungsi konversi seperti `int()` atau `float()` guna menghindari terjadinya kesalahan sistem.

**3. Konstanta dalam Bahasa Python**

Konstanta merupakan sebuah variabel khusus yang nilainya ditentukan di awal dan tidak dapat diubah setelah dideklarasikan. Secara bawaan, bahasa Python tidak memiliki kata kunci khusus untuk membuat nilai konstan secara mutlak di tingkat _runtime_. Namun, deklarasi konstanta dapat diimplementasikan dengan memanfaatkan tipe `Final` yang diimpor dari modul pustaka standar Python, yaitu `typing (from typing import Final)`.

​Penggunaan penanda `Final` berfungsi memberikan arahan kepada _type checker_ (seperti Pylance atau MyPy) bahwa nilai variabel tersebut bersifat konstan dan tidak boleh diubah di sepanjang alur program. Selain itu, berdasarkan standar panduan penulisan kode Python (_PEP 8 Style Guide_), penulisan nama variabel yang difungsikan sebagai konstanta wajib menggunakan format huruf kapital penuh, seperti contohnya `PI: Final = 3.14`.

**4. Input dan Output dalam Python**

**a. Fungsi Output (`print()`)**

​Operasi keluaran (_output_) pada Python digunakan untuk menampilkan informasi, data, atau hasil pemrosesan program ke layar terminal. Fungsi standar yang digunakan adalah `print()`. Python mendukung pemformatan string (_string formatting_) pada fungsi `print()`, seperti penggunaan _format specifier_ (contohnya `%s` untuk string, `%d` untuk integer, dan `%.2f` untuk float dengan pembulatan desimal) maupun metode modern seperti `str.format()` dan `f-string`. Karakter khusus seperti `\n` juga kerap dimanfaatkan untuk membuat baris baru pada tampilan output.

**​b. Fungsi Input (`input()`)**

​Operasi masukan (_input_) memungkinkan program untuk menerima entri data secara interaktif dari pengguna (_user_) saat program berjalan. Fungsi yang digunakan adalah `input()`, yang menerima argumen berupa teks petunjuk. Secara bawaan, semua data yang ditangkap melalui fungsi `input()` akan disimpan dalam bentuk tipe data string (`str`). Oleh karena itu, jika nilai masukan tersebut hendak digunakan dalam operasi kalkulasi atau aritmetika, proses konversi tipe data (_type casting_) ke bentuk `int` atau `float` wajib dilakukan terlebih dahulu.

<h2><b>2.2 Kode Program</b></h2>

<h3><b>2.2.1 Program "Numerik_2611532001.py"</b></h3>

In [ ]:
# Create a variable with integer value
a_2001 = 100
print("The type of variable having value", a_2001,"is", type(a_2001))

# Create a variable with float value
b_2001 = 10.2345
print("The type of variable having value", b_2001,"is", type(b_2001))

# Create a variable with complex value
c_2001 = 100+3j
print("The type of variable having value", c_2001,"is", type(c_2001))

The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (100+3j) is <class 'complex'>


**Penjelasan :**

**1. Membuat Komentar:** Sintaks
`# Create a variabel with ...` digunakan untuk membuat komentar sebagai penanda fungsi algoritma yang ada di bawahnya.

**2. Mendeklarasikan Variabel dan Nilainya:** Sintaks `a_2001`, `b_2001`, `c_2001` merupakan variabel, serta `100`, `10.2345`, `100+3j` merupakan nilai variabel yang dideklarasikan pada program "Numerik_2611532001.py". Variabel digunakan sebagai wadah penyimpanan semetara dari nilai variabel yang telah dideklarasikan, sebelum nanti di proses oleh algortima di dalamnya.

**3. Menentukan Tipe Data:** Pada sintaks `type(a_2001)`, `type(b_2001)`, `type(c_2001)`, terdapat fungsi `type()` yang berfungsi untuk menentukan tipe data dari nilai variabel yang telah di deklarasikan sebelumnya. Output yang dihasilkan nanti berformat `<class 'data_type'>`.

**4. Mengeluarkan Output Program:** Sintaks
`print("The type of variable having value", variable,"is", type(variable))` digunakan untuk mengelurkan output dari tipe data variabel beserta nilai variabelnya, dengan format "The type of variable having value `variable` is `<class 'data_type'>`"

<h3><b>2.2.2 Program "String_2611532001.py"</b></h3>

In [ ]:
# Nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
# Ganti programnya dan data masing masing

nama_2001 = "Rizki Ramadhani Al Michtari"
jenis_kelamin_2001 = 'L'
alamat_2001 = """
    Asrama Hijau Universitas Andalas
    Kecamatan Pauh
    Kota Padang
"""
agama_2001 = "Islam"

print("Nama saya adalah: ", nama_2001)
print("Jenis kelamin saya adalah: ", jenis_kelamin_2001)
print("Alamat saya adalah: ", alamat_2001)
print("Agama saya adalah: ", agama_2001)

Nama saya adalah:  Rizki Ramadhani Al Michtari
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Asrama Hijau Universitas Andalas
    Kecamatan Pauh
    Kota Padang

Agama saya adalah:  Islam


**Penjelasan :**

**1.Membuat Komentar:** Sintaks `# Nama variabel ditambah 4 digit nim terakhir contoh: nama_1234` dan # `Ganti programnya dan data masing masing` digunakan untuk membuat komentar sebagai penanda atau instruksi pengerjaan program. Komentar ini tidak akan dieksekusi oleh Python.

**2. Mendeklarasikan Variabel dan Nilainya:** Sintaks `nama_2001`, `jenis_kelamin_2001`, `alamat_2001`, dan `agama_2001` merupakan variabel yang digunakan sebagai wadah penyimpanan data sementara. Setiap variabel diberi nilainya masing-masing berupa teks biodata yang dimasukkan menggunakan operator penugasan (`=`).

**3. Menerapkan Tipe Data String (Teks):** Nilai dari variabel yang dideklarasikan menggunakan tipe data string (`str`). Terlihat penggunaan tanda petik dua (`"..."`) pada `nama_2001` dan `agama_2001`, tanda petik tunggal (`'...'`) pada `jenis_kelamin_2001`, serta tanda petik tiga (`"""..."""`) pada `alamat_2001` yang berfungsi untuk membuat tipe data string multi-baris (multiline string).

**4. Mengeluarkan Output Program:** Sintaks `print("Nama saya adalah: ", nama_2001)` dan perintah `print()` selanjutnya digunakan untuk menampilkan teks (string) beserta nilai dari masing-masing variabel ke layar output program Python.

<h3><b>2.2.3 Program "Konstanta_2611532001.py"</b></h3>

In [ ]:
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# Nama variabel ditambah 4 digit nim terakhir contoh: jari_1234

from typing import Final
PI: Final = 3.14

print("pi: %f" % (PI))

jari_2001 = float(input('Masukkan nilai jari-jari: '))
luas_2001 = PI * jari_2001 * jari_2001

print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_2001, luas_2001))

pi: 3.140000
Masukkan nilai jari-jari: 8
Luas lingkaran dengan jari-jari 8.00 adalah 200.96


**Penjelasan :**

**1. ​Membuat Komentar:** Sintaks `# Program ini menggunakan konstanta untuk menghitung luas lingkaran` dan `# Nama variabel ditambah 4 digit nim terakhir contoh: jari_1234` digunakan sebagai komentar untuk memberikan keterangan mengenai alur serta instruksi penamaan variabel pada program.

**2. Mendeklarasikan Konstanta:** Sintaks `from typing import Final` dan `PI: Final = 3.14` digunakan untuk mengimpor modul `Final` agar variabel `PI` diperlakukan sebagai konstanta. Nilai 3,14 dialokasikan sebagai nilai tetap yang tidak boleh diubah sepanjang program dieksekusi.

**3. Menerapkan Input Data dan Konversi Tipe Data (_Type Casting_):** Sintaks `jari_2001 = float(input('Masukkan nilai jari-jari: '))` berfungsi untuk menerima input dari pengguna. Fungsi `float()` digunakan untuk mengonversi data input (yang secara bawaan bertipe string) menjadi tipe data bilangan desimal (float) agar dapat digunakan dalam operasi perhitungan matematika.

**4. Memproses Perhitungan Aritmetika:** Sintaks `luas_2001 = PI * jari_2001 * jari_2001` merupakan proses algortima penghitungan untuk menghitung luas lingkaran berdasarkan rumus L = $\pi$ × r². Hasil perkalian antara konstanta `PI` dan variabel `jari_2001` disimpan ke dalam variabel `luas_2001`.

**5. Mengeluarkan Output dengan Format String:** Sintaks `print("pi: %f" % (PI))` dan `print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_2001, luas_2001))` digunakan untuk menampilkan hasil program ke layar output atau terminal. Penulisan `%f` dan `%.2f` merupakan format spesifim yang berfungsi menampilkan nilai float, di mana `%.2f` membatasi pembulatan tampilan angka desimal hingga dua digit di belakang koma.

<h3><b>2.2.4 Program "Input_2611532001.py"</b></h3>

In [ ]:
# Buat program untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit nim terakhir contoh: panjang 1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# Memasukkan nilai panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer

panjang_2001 = input('Masukkan nilai panjang: ')
lebar_2001 = input('Masukkan nilai lebar: ')

luas_2001 = int(panjang_2001) * int(lebar_2001)
print("Luas = ", luas_2001)

Masukkan nilai panjang: 8
Masukkan nilai lebar: 5
Luas =  40


**Penjelasan :**

**1. ​Membuat Komentar:** Sintaks diawali tanda `#` (seperti `# Buat program untuk menghitung luas persegi panjang`) digunakan sebagai komentar penjelas yang berisi deskripsi alur program, aturan penamaan variabel, serta instruksi penggunaan fungsi `input()` dan konversi tipe data.

**2. ​Menerapkan Input Data dari Pengguna:** Sintaks `panjang_2001 = input('Masukkan nilai panjang: ')` dan `lebar_2001 = input('Masukkan nilai lebar: ')` digunakan untuk menerima input teks dari pengguna melalui terminal. Nilai masukan tersebut secara bawaan bertipe data string dan disimpan masing-masing ke dalam variabel `panjang_2001` serta `lebar_2001`.

**3. ​Melakukan Konversi Tipe Data (Type Casting) dan Operasi Aritmetika:** Sintaks `luas_2001 = int(panjang_2001) * int(lebar_2001)` menggunakan fungsi `int()` untuk mengonversi nilai variabel `panjang_2001` dan `lebar_2001` dari string menjadi bilangan bulat (integer). Setelah dikonversi, kedua nilai tersebut dikalikan dengan operator aritmetika `*` untuk menghitung luas persegi panjang, lalu hasilnya disimpan ke dalam variabel `luas_2001`.

**4. Mengeluarkan Output Program:** Sintaks `print("Luas = ", luas_2001)` digunakan untuk menampilkan teks label "Luas = " beserta nilai hasil perhitungan yang tersimpan pada variabel `luas_2001` ke layar output atau terminal.

<h3><b>2.2.5 Program "Boolean_2611532001.py"</b></h3>

In [ ]:
# Nama variabel ditambah 4 digit nim terakhir contoh: nama_1234
# Deklarasi variabel dengan tipe data Boolean

is_lulus_2001 = True
is_cumlaude_2001 = True

# Menggunakan boolean
nilai_2001 = 85
batas_lulus_2001 = 75

# Menentukan nilai boolean dari kondisi
status_kelulusan_2001 = nilai_2001 >= batas_lulus_2001 # Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai: ", nilai_2001)
print("Apakah lulus?: ", status_kelulusan_2001)
if is_lulus_2001 and is_cumlaude_2001:
    print("Selamat, Anda lulus dengan predikat Cum Laude!")

=== Check Kelulusan ===
Nilai:  85
Apakah lulus?:  True
Selamat, Anda lulus dengan predikat Cum Laude!


**Penjelasan :**

**1. Membuat Komentar:** Sintaks diawali tanda `#` (seperti `# Deklarasi variabel dengan tipe data Boolean` dan `# Menentukan nilai boolean dari kondisi`) digunakan sebagai komentar penjelas untuk memberikan instruksi pengerjaan serta petunjuk alur logika program.

**2. ​Mendeklarasikan Variabel dan Tipe Data Boolean:** Sintaks `is_lulus_2001 = True` dan `is_cumlaude_2001 = True` digunakan untuk mendeklarasikan variabel dengan tipe data boolean (`bool`). Tipe data ini hanya menyimpan salah satu dari dua nilai kebenaran logika, yaitu `True` (benar) atau `False` (salah).

**3. ​Mendeklarasikan Variabel Numerik:** Sintaks `nilai_2001 = 85` dan `batas_lulus_2001 = 75` merupakan deklarasi variabel bertipe data integer (`int`) yang menyimpan nilai angka bulat untuk acuan evaluasi kondisi.

**4. ​Evaluasi Kondisi Menggunakan Operator Perbandingan:** Sintaks `status_kelulusan_2001 = nilai_2001 >= batas_lulus_2001` memanfaatkan operator perbandingan lebih besar dari atau sama dengan (`>=`). Hasil perbandingan antara 85 $\ge$ 75 menghasilkan nilai logika `True`, yang kemudian disimpan ke dalam variabel `status_kelulusan_2001`.

**5. Mengeluarkan Output dan Evaluasi Kondisi Logika:** Sintaks `print()` digunakan untuk menampilkan informasi nilai dan status kelulusan. Selanjutnya, sintaks `if is_lulus_2001 and is_cumlaude_2001:` menggunakan struktur kendali `if` dan operator logika `and`. Karena kedua variabel bernilai `True`, kondisi terpenuhi sehingga pesan ucapan selamat lulus cum laude dicetak ke layar output.

---
<div align="center">

<h1><b>BAB III</b><h1>

<h1><b>KESIMPULAN</b></h1>

</div>

Berdasarkan praktikum yang telah dilaksanakan, dapat ditarik kesimpulan bahwa:

* **​Variabel dan Tipe Data:** Variabel pada Python bersifat _dynamic typing_ (tidak perlu deklarasi tipe data secara manual) dan dapat menyimpan berbagai tipe data dasar seperti string (`str`), integer (`int`), float (`float`), dan boolean (`bool`).

* **​Penggunaan Konstanta:** Deklarasi nilai tetap/konstanta dapat dilakukan menggunakan `Final` dari modul `typing` untuk menjaga nilai variabel agar tidak diubah secara tidak sengaja di sepanjang program.

* **​Fungsi Input dan Type Casting:** Fungsi `input()` secara bawaan selalu menghasilkan tipe data string. Oleh karena itu, konversi tipe data (_type casting_) seperti `int()` atau `float()` mutlak diperlukan sebelum data digunakan dalam operasi aritmetika.

* **​Operasi Logika dan Output:** Tipe data boolean dapat dihasilkan melalui operator perbandingan (seperti `>=`) dan dikombinasikan dengan operator logika (`and`) pada struktur kendali `if`, sedangkan fungsi `print()` dapat diformat (misal `%.2f`) untuk menampilkan output angka desimal secara rapi.

---
<div align="center">

<h1><b>DAFTAR PUSTAKA</b></h1>

</div>

[1] ​Dicoding Intern. (2023, 31 Mei). Python: Pengertian, Contoh Penggunaan, dan Manfaat Mempelajarinya. Blog Dicoding Indonesia. https://www.dicoding.com/blog/python-pengertian-contoh-penggunaan-dan-manfaat-mempelajarinya/

[2] Rafifah, A. (2025, 16 Juni). Belajar Python Part 2: Variabel, Tipe Data, dan Operator. Rumahweb Journal. https://www.rumahweb.com/journal/belajar-python-part-2/

[3] ​Agung, N. (2026). A.5. Python Konstanta. Dasar Pemrograman Python. https://dasarpemrogramanpython.novalagung.com/basic/konstanta