print("╔══════════════════════════════╗")
print("║       PYTHON RANDOMIZER      ║")
print("╠══════════════════════════════╣")
print("║                              ║")
print("║  Memutar keberuntungan...    ║")
print("║                              ║")
print("║  [████████████████████] 100% ║")
print("║                              ║")
print("║  HASIL:                      ║")
print("║                              ║")
print("║        Kamu mendapatkan      ║")
print("║                              ║")
print("║             KENTANG          ║")
print("║                              ║")
print("╚══════════════════════════════╝")