print("==============================")
print("       BIODATA MAHASISWA")
print("==============================")
print("Nama       : Rizki")
print("Jurusan    : Informatika")
print("Universitas: Universitas Andalas")
print("Status     : Mahasiswa")
print("Hobi       : Coding & Baca Novel")
print("Cita-cita  : AI Engineer")
print("==============================")